### ISSUE TITLE
compatibility issue

### ISSUE THREAD

**Issue by CodeLiSW** [lostkevin/kfblibrary#2]
First, thanks a lot.
I found this memory leaking issue recently, but I don't know much about c++/c.
When I compile this project with comand:
g++ -shared -o libkfbslide.so kfbreader.cpp
and replace libkfbslide.so, errors occur:

Exception has occurred: AttributeError
/home/ll/miniconda3/envs/kpcelldet_base/lib/python3.6/site-packages/tslide/kfb/lib/libkfbslide.so: undefined symbol: kfbslide_get_image_roi_stream
File "/gpfsdata/home/ll/kp_project/scripts/data_process/testso.py", line 2, in <module>
from tslide.aslide import Slide
AttributeError: /home/ll/miniconda3/envs/kpcelldet_base/lib/python3.6/site-packages/tslide/kfb/lib/libkfbslide.so: undefined symbol: kfbslide_get_image_roi_stream

do you have any ideas about this?

**Comment by lostkevin** [comment]
C++ will modify the function signature automatically to support overload. You need to replace the symbol name with the corresponding symbol in the compiled library. You can get the symbol name with decompilers like IDA.

**Comment by lostkevin** [comment]
You can also refer to this link: https://stackoverflow.com/questions/34732/how-do-i-list-the-symbols-in-a-so-file

**Comment by CodeLiSW** [comment]
> C++ will modify the function signature automatically to support overload. You need to replace the symbol name with the corresponding symbol in the compiled library. You can get the symbol name with decompilers like IDA.

It seems the symbol name in my project is the same to the corresponding symbol in the compiled library.
I did:
`nm -gD libkfbslide.so | grep kfbslide`
and got ( the 7th line):

0000000000015fad T kfbslide_buffer_free
00000000000150bd T kfbslide_close
0000000000015138 T kfbslide_detect_vendor
000000000001553f T kfbslide_get_associated_image_dimensions
00000000000156e3 T kfbslide_get_associated_image_names
00000000000152af T kfbslide_get_best_level_for_downsample
**0000000000015e62 T kfbslide_get_image_roi_stream**
0000000000015325 T kfbslide_get_level_count
0000000000015336 T kfbslide_get_level_dimensions
0000000000015275 T kfbslide_get_level_downsample
0000000000014a5b T kfbslide_open
0000000000015264 T kfbslide_property_names
0000000000015149 T kfbslide_property_value
00000000000153c9 T kfbslide_read_associated_image
0000000000015d3e T kfbslide_read_region

In my project, I defined this func:
`_kfbslide_read_roi_region = _func("kfbslide_get_image_roi_stream", c_bool, [_KfbSlide, c_int32, c_int64, c_int64, c_int64, c_int64, POINTER(c_int), POINTER(POINTER(c_ubyte))])`

`_lib = cdll.LoadLibrary('libkfbslide.so')`
`def _func(name, restype, argtypes, errcheck=_check_error):`
`    func = getattr(_lib, name)`
`    func.argtypes = argtypes`
`    func.restype = restype`
`    if errcheck is not None:`
`        func.errcheck = errcheck`
`    return func`

maybe i misunderstand your comments, do u mean i need to modify the name in '_func' to be the same with the symbol in .so file?

**Comment by lostkevin** [comment]
Did you add `-fPIC` option in compiling?

**Comment by CodeLiSW** [comment]
I recompile with command `g++ -fPIC -shared -o libkfbslide.so kfbreader.cpp -ldl`, and try again, and now this problem pass, but get another "invalid ELF header"  when it run 'kfbslide_open'.  
do u have any demo code for using libkfbslide.so?
Thanks a lot.

**Comment by lostkevin** [comment]
I use the following commands to run the C++ Demo:
 
```
g++ -c -g kfbreader.cpp -o kfbreader.o
g++  -g main.cpp kfbreader.o -o main -ldl
LD_LIBRARY_PATH=/path/to/libjpeg_and_other_dependency  ./main
``` 

and the dynamic library is compiled with:

```
g++  -fPIC kfbreader.cpp -o libkfbreader.so -ldl -shared -O2
``` 

Python Demo:

```python3
from ctypes import *
from openslide import lowlevel
from ctypes.util import find_library

_reader_path = './libkfbreader.so'
_lowlevel_path = find_library('ImageOperationLib')

_lib = cdll.LoadLibrary(_reader_path)
_libimgop = _lowlevel_path

class KFBSlideError(Exception):
    """docstring for KFBSlideError"""

class _KfbSlide(object):
    def __init__(self, ptr):
        self._as_parameter_ = ptr
        self._valid = True
        self._close = kfbslide_close # 即使调用了close，资源也不能正确释放

    def __del__(self):
        if self._valid:
            self._close(self)

    def invalidate(self):
        self._valid = False

    @classmethod
    def from_param(cls, obj):
        if obj.__class__ != cls:
            raise ValueError("Not an KfbSlide reference")
        if not obj._as_parameter_:
            raise ValueError("Passing undefined slide object")
        if not obj._valid:
            raise ValueError("Passing closed kfbSlide object")
        return obj


# check for errors opening an image file and wrap the resulting handle
def _check_open(result, _func, _args):
    if result is None:
        raise lowlevel.OpenSlideUnsupportedFormatError(
            "Unsupported or missing image file")
    slide = _KfbSlide(c_void_p(result))
    # err = get_error(slide)
    # if err is not None:
    #     raise lowlevel.OpenSlideError(err)
    return slide

# check if the library got into an error state after each library call
def _check_error(result, func, args):
    # err = get_error(args[0])
    # if err is not None:
    #     raise lowlevel.OpenSlideError(err)
    return lowlevel._check_string(result, func, args)

# resolve and return an OpenSlide function with the specified properties
def _func(name, restype, argtypes, errcheck=_check_error):
    func = getattr(_lib, name)
    func.argtypes = argtypes
    func.restype = restype
    if errcheck is not None:
        func.errcheck = errcheck
    return func

_kfbslide_open = _func("kfbslide_open", c_void_p, [lowlevel._utf8_p, lowlevel._utf8_p], _check_open)

_kfbslide_get_level_dimensions = _func("kfbslide_get_level_dimensions", None,
                                       [_KfbSlide, c_int32, POINTER(c_int64), POINTER(c_int64)])

kfbslide_close = _func("kfbslide_close", None, [_KfbSlide], lowlevel._check_close)

def kfbslide_open(name):
    osr = _kfbslide_open(_libimgop, name)
    return osr

def kfbslide_get_level_dimensions(osr, level):
    w, h = c_int64(), c_int64()
    _kfbslide_get_level_dimensions(osr, level, byref(w), byref(h))
    return (w.value, h.value)


osr = kfbslide_open("/path/to/kfb/file")
print(kfbslide_get_level_dimensions(osr, 1))

``` 

Run Python Demo by:
```
LD_LIBRARY_PATH=/path/to/libjpeg_and_other_dependency  python test.py
```

**Comment by CodeLiSW** [comment]
Really appreciate your help! I finally solve it and have a new look about how to invoke an API from C library in python.

I didn't align the input args between python and C programs.

old code (bug):
```python
_kfbslide_open = _func("kfbslide_open", c_void_p, [lowlevel._utf8_p], _check_open)

def kfbslide_open(name):
    osr = _kfbslide_open(name)
    return osr
```
revised code:
```python
_kfbslide_open = _func("kfbslide_open", c_void_p, [lowlevel._utf8_p, lowlevel._utf8_p], _check_open)

def kfbslide_open(name):
    osr = _kfbslide_open(_libimgop, name)
    return osr
```

Also, for the api 'kfbslide_read_associated_image'

old code:
```python
_kfbslide_read_associated_image = _func("kfbslide_read_associated_image", c_void_p, [_KfbSlide, lowlevel._utf8_p, POINTER(POINTER(c_ubyte))])

def kfbslide_read_associated_image(osr, name):
    data_length = kfbslide_get_associated_image_dimensions(osr, name)[1]
    pixel = POINTER(c_ubyte)()

    _kfbslide_read_associated_image(osr, name, byref(pixel))
    
    import numpy as np
    narray = np.ctypeslib.as_array(pixel, shape=(data_length,))
    from io import BytesIO
    buf = BytesIO(narray)
    from PIL import Image
    return Image.open(buf)
```

revised code:
```python
_kfbslide_read_associated_image = _func("kfbslide_read_associated_image", POINTER(c_ubyte), [_KfbSlide, lowlevel._utf8_p])

def kfbslide_read_associated_image(osr, name):
    data_length = kfbslide_get_associated_image_dimensions(osr, name)[1]
    pixel = POINTER(c_ubyte)()

    pixel = _kfbslide_read_associated_image(osr, name)
    
    import numpy as np
    narray = np.ctypeslib.as_array(pixel, shape=(data_length,))
    from io import BytesIO
    buf = BytesIO(narray)
    from PIL import Image
    return Image.open(buf)
```

Hope this will help.
